spring.application.name=AfyaFlow

spring.datasource.url=jdbc:mysql://localhost:3306/afyaflowdb
spring.datasource.username=root
spring.datasource.password= afyaflow

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080
